# Generated by Django 3.2.6 on 2021-10-13 12:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 10, 13, 12, 25, 14, 283036, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
