# Generated by Django 3.2.6 on 2021-10-17 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_pupil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pupil',
        ),
    ]
